// Compile-only integration smoke test. Do not run this on a connected hardware project.
input.onButtonPressed(Button.AB, function () {
    Displays01.lcdShowString("BRIXEL", 0, 0)
    let strip = Displays01.neopixelCreate(DigitalPin.P1, 4, Displays01.NeoPixelFormat.RGB)
    Displays01.neopixelShowColor(strip, 0xff0000)
    AdvDisplays.ht16k33SetBrightness(1)
    Sensors03.mhz19Read(<Sensors03.MHZ19DataType>0)
    Sensors03.hiTempReadRaw()
    Sensors03.voltageRead(AnalogPin.P1, 5)
    AdvSensors.sht30ReadHumidity()
    AdvSensors.i2cWeightRead()
    Actuators05.servoSetAngle(AnalogPin.P1, 90)
    Actuators05.l298nMotorA(0)
    OutputDevice.buzzerSetBPM(120)
    Communications07.irInit(DigitalPin.P16)
    WiFi08.wifiIsConnected()
    USBSerial.serialSend("123")
    Bluetooth10.btStart()
    Bluetooth10.btSend("123")
    AdvSensors.i2cWeightTare(5)
})
