// Execute the actual TypeScript with fake IO. This does not emulate CODAL timing or physical hardware.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
try { require('pxt-core/built/pxt.js'); }
catch (e) { require('../../_pxtws/node_modules/pxt-core/built/pxt.js'); }
const root=path.resolve(__dirname,'..'),cfg=JSON.parse(fs.readFileSync(path.join(root,'pxt.json')));
const source=cfg.files.filter(f=>f.endsWith('.ts')).map(f=>fs.readFileSync(path.join(root,f),'utf8')).join('\n');
const js=ts.transpile(source,{target:ts.ScriptTarget.ES2017,module:ts.ModuleKind.None});
function env(){
 const state={ms:100,adc:512,adcValues:[],numReads:[],bufReads:[],rx:[],strings:[],writes:[],background:[],pulse:5831};
 const buf=(data)=>{let b=typeof data==='number'?Buffer.alloc(data):Buffer.from(data);b.getNumber=(fmt,off)=>{let n=b[off]||0;if(String(fmt).includes('16'))n=String(fmt).endsWith('BE')?(n<<8)|(b[off+1]||0):n|((b[off+1]||0)<<8);return n};b.setNumber=(fmt,off,v)=>{b[off]=v&255;b[off+1]=(v>>>8)&255};return b};
 const math=Object.create(Math);math.clamp=(lo,hi,v)=>Math.min(hi,Math.max(lo,v));math.constrain=(v,lo,hi)=>math.clamp(lo,hi,v);math.map=(v,a,b,c,d)=>c+(v-a)*(d-c)/(b-a);math.idiv=(a,b)=>Math.trunc(a/b);
 const log=(name,...args)=>state.writes.push([name,...args]);
 const pins={createBuffer:buf,createBufferFromArray:buf,createBufferFromUTF8:s=>buf(Buffer.from(s)),analogReadPin:()=>state.adcValues.length?state.adcValues.shift():state.adc,
 i2cWriteNumber:(...a)=>log('i2cN',...a),i2cWriteBuffer:(a,b)=>log('i2cB',a,[...b]),i2cReadNumber:()=>state.numReads.shift()||0,i2cReadBuffer:(a,n)=>buf(state.bufReads.shift()||Array(n).fill(0)),
 digitalWritePin:(...a)=>log('digital',...a),analogWritePin:(...a)=>log('analog',...a),servoWritePin:(...a)=>log('servo',...a),servoSetPulse:(...a)=>log('servoPulse',...a),digitalReadPin:()=>0,pulseIn:()=>state.pulse,
 setPull:()=>{},setAudioPinEnabled:()=>{},analogSetPeriod:()=>{},spiPins:()=>{},spiFormat:()=>{},spiFrequency:()=>{},spiWrite:()=>0};
 const serial={readBuffer:()=>buf(state.rx.shift()||[]),readString:()=>state.strings.shift()||'',writeBuffer:b=>{log('serialB',[...b]);if(state.onWrite)state.onWrite(b)},writeString:s=>{log('serialS',s);if(state.onString)state.onString(s)},writeLine:s=>log('serialL',s),redirect:(...a)=>log('redirect',...a),setRxBufferSize:()=>{},setWriteLinePadding:()=>{}};
 const pause=n=>{state.ms+=Math.max(1,n);if(state.stopBackground)throw 'one-tick';};
 const c={pins,serial,Math:math,console,parseInt,parseFloat,isNaN,Buffer:{fromUTF8:s=>buf(Buffer.from(s))},hex:s=>buf(Buffer.from(s[0].replace(/\s/g,''),'hex')),
 basic:{pause},control:{millis:()=>state.ms,micros:()=>state.ms*1000,waitMicros:n=>{state.ms+=n/1000},inBackground:f=>state.background.push(f),raiseEvent:()=>{},onEvent:()=>{}},
 led:{enable:()=>{}},input:{runningTime:()=>state.ms},music:{setVolume:()=>{},setTempo:()=>{},playTone:()=>{},stopAllSounds:()=>{}},bluetooth:{},ws2812b:{},BrixelNative:{sampleDust:()=>state.adc}};
 for(const name of ['AnalogPin','DigitalPin','SerialPin','BaudRate','PinPullMode','PulseValue','NumberFormat','PinEventType','BeatFraction','NeoPixelMode','BaudRate'])
  c[name]=new Proxy({}, {get:(o,k)=>name==='NumberFormat'?k:(/^P\d+$/.test(k)?parseInt(k.slice(1)):/BaudRate\d+/.test(k)?parseInt(k.slice(8)):0)});
 vm.createContext(c);vm.runInContext('Array.prototype.removeAt=function(i){return this.splice(i,1)[0]};',c);vm.runInContext(js,c,{timeout:3000});
 c.BrixelNative.sampleDust=()=>state.adcValues.length?state.adcValues.shift():state.adc;
 return {c,state,buf,tick(){state.stopBackground=true;try{state.background[0]()}catch(e){if(e!=='one-tick')throw e}finally{state.stopBackground=false}}};
}
const cases=[];function test(name,fn){cases.push([name,fn])}
const near=(x,y,eps=0.02)=>assert(Math.abs(x-y)<=eps,`${x} != ${y}`);
test('ADC voltage divider: 0V / half / full scale',()=>{const {c,state}=env();for(const [raw,v]of[[0,0],[512,8.26],[1023,16.5]]){state.adc=raw;near(c.Sensors03.voltageRead(0,25),v)}});
test('HC-SR04: 5831us equals 100cm',()=>{const {c}=env();near(c.Sensors03.hcsr04Read(c.Sensors03.DistanceUnit.CM||0),100)});
test('MAX30102: stale data must clear finger/ready',()=>{const e=env(),a=e.c.AdvSensors;a.heartRateSetup();e.state.numReads=[1,0];e.state.bufReads=[[1,0,0,1,0,0]];a.heartRateFingerDetected();a.heartRateGetBPM();e.state.ms+=6000;e.tick();assert.equal(a.heartRateFingerDetected(),false);assert.equal(a.heartRateIsReady(),false)});
test('GPS: valid NMEA then receive timeout clears FIX',()=>{const {c,state}=env();state.strings=['$GPGGA,123519,4807.038,N,01131.000,E,1,08,0.9,545.4,M,46.9,M,,*47\r\n'];c.Communications07.gpsUpdate();assert.equal(c.Communications07.gpsHasFix(),true);state.ms+=11000;c.Communications07.gpsUpdate();assert.equal(c.Communications07.gpsHasFix(),false)});
function nmea(body){let n=0;for(const char of body)n^=char.charCodeAt(0);return '$'+body+'*'+n.toString(16).padStart(2,'0')+'\r\n'}
test('GPS: RMC updates coordinates/time; unrelated fields expire; void status invalidates location',()=>{const {c,state}=env(),g=c.Communications07;state.strings=[nmea('GPGGA,123519,4807.038,N,01131.000,E,1,08,0.9,545.4,M,46.9,M,,')];g.gpsUpdate();near(g.gpsRead(g.GPSData.Altitude),545.4);state.ms+=3500;state.strings=[nmea('GNRMC,123523,A,4907.038,N,01231.000,E,1.5,23.4,081026,,,A')];g.gpsUpdate();assert.equal(g.gpsHasFix(),true);near(g.gpsRead(g.GPSData.Latitude),49.1173);assert.equal(g.gpsGetTime(),'12:35:23');assert.equal(g.gpsGetDate(),'08/10/2026');assert.equal(g.gpsRead(g.GPSData.Altitude),-9999);state.strings=[nmea('GNRMC,123524,V,,,,,,,081026,,,N')];g.gpsUpdate();assert.equal(g.gpsHasFix(),false);assert.equal(g.gpsRead(g.GPSData.Latitude),-9999)});
test('MH-Z19D: init preserves ABC, warm-up, good frame, CRC error and timeout',()=>{const {c,state}=env();c.Sensors03.mhz19Init(13,14,9600);assert(!state.writes.some(w=>w[0]==='serialB'));assert.equal(c.Sensors03.mhz19Read(0),-1);state.ms+=60000;state.onWrite=()=>state.rx.push([255,134,3,32,65,0,0,0,22]);assert.equal(c.Sensors03.mhz19Read(0),800);state.onWrite=()=>state.rx.push([255,134,3,32,65,0,0,0,0]);assert.equal(c.Sensors03.mhz19Read(0),-1);state.onWrite=null;assert.equal(c.Sensors03.mhz19Read(0),-1)});
test('Turbidity: uncalibrated must not report clean-water zero',()=>{const {c}=env();c.Sensors03.turbidityInit(0);assert.equal(c.Sensors03.turbidityRead(0),-1)});
test('RTC: setting writes BCD and starts clock',()=>{const {c,state}=env();c.AdvSensors.rtcSetTime(0x68,2026,10,8,12,34,56);const w=state.writes.filter(x=>x[0]==='i2cB');assert.deepEqual(w[w.length-1],['i2cB',0x68,[0,0x56]])});
test('WCS2801: zero, reference, signed current, range and recalibration failure',()=>{const {c,state}=env(),s=c.Sensors03;assert.equal(s.currentAmps(1),-9999);state.adc=512;s.zeroCurrent(1);state.adc=612;s.calibrateCurrent(1,0.5);near(s.currentAmps(1),0.5);state.adc=412;near(s.currentAmps(1),-0.5);state.adc=900;assert.equal(s.currentAmps(1),-9999);s.calibrateCurrent(1,0);assert.equal(s.currentAmps(1),-9999);s.zeroCurrent(1);assert.equal(s.currentAmps(1),-9999)});
test('Voltage calibration: zero is valid, saturation and unstable reference rejected',()=>{const {c,state}=env(),s=c.Sensors03;assert.equal(s.voltageCalibrated(1),-1);state.adc=310;s.calibrateVoltage(1,5);near(s.voltageCalibrated(1),5);state.adc=0;assert.equal(s.voltageCalibrated(1),0);state.adc=1023;assert.equal(s.voltageCalibrated(1),-1);state.adcValues=[100,200,...Array(14).fill(150)];s.calibrateVoltage(1,5);assert.equal(s.voltageCalibrated(1),-1)});
test('AZDM01: relative transmission and failed re-zero',()=>{const {c,state}=env(),s=c.Sensors03;state.adc=800;s.calibrateTurbidity(1);state.adc=400;near(s.turbidityTransmission(1),50);state.adc=0;assert.equal(s.turbidityTransmission(1),0);s.calibrateTurbidity(1);assert.equal(s.turbidityTransmission(1),-1)});
test('UV: voltage works uncalibrated; index and irradiance references are independent',()=>{const {c,state}=env(),s=c.Sensors03;s.uvInit(1);assert(s.uvRead(1)>0);assert.equal(s.uvRead(0),-1);state.adc=10;s.uvCalibrate(0,0);state.adc=110;s.uvSetReference(0,4);near(s.uvRead(0),4);assert.equal(s.uvRead(2),-1);s.uvSetReference(2,0.5);near(s.uvRead(2),0.5);s.uvCalibrate(1,2800);assert.equal(s.uvRead(0),-1);assert.equal(s.uvRead(2),-1)});
test('Dust: 8-sample raw mean, invalid pins and sampling failure',()=>{const {c,state}=env(),s=c.Sensors03;state.adcValues=[100,110,120,130,140,150,160,170];assert.equal(s.analogDustRaw(1,8),135);assert.equal(s.analogDustRaw(1,1),-1);assert.equal(s.analogDustRaw(8,12),-1);state.adcValues=[-1];assert.equal(s.analogDustRaw(1,8),-1)});
test('PCA9685: 50Hz, channel16 register, full-off, invalid inputs cause no writes',()=>{const {c,state}=env(),a=c.Actuators05;a.pca9685ServoPulse(0x41,16,1500);assert(state.writes.some(w=>w[0]==='i2cN'&&w[2]===0xFE79));assert.deepEqual(state.writes.at(-1),['i2cB',0x41,[66,0,0,51,1]]);a.pca9685ServoRelease(0x41,16);assert.deepEqual(state.writes.at(-1),['i2cB',0x41,[66,0,0,0,16]]);let n=state.writes.length;for(const ch of [0,17,1.5])a.pca9685ServoPulse(0x41,ch,1500);a.pca9685ServoPulse(0x70,1,1500);a.pca9685ServoPulse(0x41,1,NaN);assert.equal(state.writes.length,n)});
test('PCA9685: DC then servo then DC restores shared chip frequency',()=>{const {c}=env(),a=c.Actuators05;a.pca9685DcMotorSetup(1,0x40);assert.equal(a.pca9685Frequency(0x40),1000);a.pca9685ServoAngle(0x40,1,90);assert.equal(a.pca9685Frequency(0x40),50);a.pca9685DcMotorWheelA(1,0,50);assert.equal(a.pca9685Frequency(0x40),1000)});
test('APDS9960: both reporter styles share one FIFO gesture and expiry',()=>{const {c,state}=env(),a=c.AdvSensors;state.numReads=[1,5];state.bufReads=[[100,20,50,50],[80,40,50,50],[60,60,50,50],[40,80,50,50],[20,100,50,50]];assert.equal(a.apds9960ReadGesture(),a.APDS9960Gesture.Up);state.ms+=350;assert.equal(a.apds9960GetGesture(a.APDS9960GestureKR.Up),true);state.ms+=100;assert.equal(a.apds9960GetGesture(a.APDS9960GestureKR.Up),false);assert.equal(a.apds9960ReadGesture(),a.APDS9960Gesture.None)});
function wsEnv(){const e=env(),sent=[],messages=[],w=e.c.BrixelWebSocket;w.configure((id,b)=>{sent.push([id,Buffer.from(b)]);return true},(id,t)=>messages.push([id,t]));return {...e,w,sent,messages}}
const handshake='GET / HTTP/1.1\r\nHost: lab\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\nSec-WebSocket-Version: 13\r\n\r\n';
function masked(text,op=1,fin=true){const b=Buffer.isBuffer(text)?text:Buffer.from(text),mask=Buffer.from([1,2,3,4]);const header=b.length<126?Buffer.from([(fin?128:0)|op,128|b.length]):Buffer.from([(fin?128:0)|op,254,b.length>>8,b.length&255]);return Buffer.concat([header,mask,Buffer.from(b.map((v,i)=>v^mask[i%4]))]).toString('latin1')}
test('WebSocket: RFC handshake SHA1 vector and split request',()=>{const {w,sent}=wsEnv();assert.equal(w.acceptKey('dGhlIHNhbXBsZSBub25jZQ=='),'s3pPLMBiTxaQ9kYGzzhZRbK+xOo=');w.feed(0,handshake.slice(0,60));assert.equal(sent.length,0);w.feed(0,handshake.slice(60));assert(sent[0][1].toString().includes('101 Switching Protocols'));assert(sent[0][1].toString().includes('s3pPLMBiTxaQ9kYGzzhZRbK+xOo='))});
test('WebSocket: masked Korean text, TCP split, continuation and ping/pong',()=>{const {w,sent,messages}=wsEnv();w.feed(0,handshake);let m=masked('온도 25');w.feed(0,m.slice(0,7));assert.equal(messages.length,0);w.feed(0,m.slice(7));assert.deepEqual(messages,[[0,'온도 25']]);w.feed(0,masked('hel',1,false)+masked('?',9)+masked('lo',0,true));assert.deepEqual(messages.at(-1),[0,'hello']);assert.equal(sent.at(-1)[1][0],0x8a);w.sendText(0,'한글');assert.equal(sent.at(-1)[1][1],6);assert.equal(sent.at(-1)[1].subarray(2).toString(),'한글')});
test('WebSocket: reject unmasked/oversize/invalid UTF8 and keep clients separate',()=>{for(const raw of ['\x81\x01x','\x81\xff',masked(Buffer.from([0xff]))]){const {w,sent,messages}=wsEnv();w.feed(0,handshake);w.feed(0,raw);assert.equal(messages.length,0);assert.equal(sent.at(-1)[1][0],0x88);assert.equal(w.sendText(0,'x'),false)}const {w,messages}=wsEnv();w.feed(1,handshake);w.feed(1,masked('A'));w.feed(2,handshake+masked('B'));assert.deepEqual(messages,[[1,'A'],[2,'B']]);assert.equal(w.sendText(1,'a'.repeat(1025)),false)});
test('WebSocket: invalid upgrade rejected; closed socket requires handshake again',()=>{const {w,sent}=wsEnv();w.feed(0,handshake.replace('Version: 13','Version: 12'));assert(sent[0][1].toString().startsWith('HTTP/1.1 400'));w.feed(0,handshake);w.feed(0,masked('',8));assert.equal(w.sendText(0,'x'),false);w.feed(0,handshake);assert.equal(w.sendText(0,'x'),true)});
test('HC-SR04: no echo is failure, not 0cm',()=>{const {c,state}=env();state.pulse=0;assert.equal(c.Sensors03.hcsr04Read(0),-1)});
test('US-100: no echo is failure, not 0cm',()=>{const {c,state}=env();state.pulse=0;assert.equal(c.Sensors03.us100Read(0),-1)});
test('MH-Z19 status: missing response is unknown, not cached default',()=>{const {c}=env();assert.equal(c.Sensors03.mhz19GetStatus(0),-1);c.Sensors03.mhz19Init(13,14,9600);assert.equal(c.Sensors03.mhz19GetStatus(0),-1);assert.equal(c.Sensors03.mhz19GetStatus(1),-1)});
test('CCS811: data ready, sibling reporter cache, stale and error invalidation',()=>{const {c,state}=env(),a=c.AdvSensors;a.ccs811Init();state.numReads=[0x98,0x90];state.bufReads=[[3,32,0,12,0x98,0,0,0]];assert.equal(a.ccs811Read(0),800);assert.equal(a.ccs811Read(1),12);state.ms+=2600;state.numReads=[0x90];assert.equal(a.ccs811Read(0),-1);state.numReads=[0x91,2];assert.equal(a.ccs811Read(1),-1);state.numReads=[0];assert.equal(a.ccs811Read(0),-1)});
function crc8(a,b){let c=255;for(let d of[a,b]){c^=d;for(let i=0;i<8;i++)c=(c&128)?((c<<1)^0x31)&255:(c<<1)&255}return c}
test('SGP30: startup, warmup, CRC, measurement freshness and restart',()=>{const {c,state}=env(),a=c.AdvSensors;assert.equal(a.sgp30Read(0),-1);state.ms=0;a.sgp30Init();state.bufReads=[[1,144,crc8(1,144),0,0,crc8(0,0)]];a.sgp30Measure();assert.equal(a.sgp30Read(0),-1);state.ms=16000;assert.equal(a.sgp30Ready(),true);state.bufReads=[[3,32,crc8(3,32),0,12,crc8(0,12)]];a.sgp30Measure();assert.equal(a.sgp30Read(0),800);state.ms+=2600;assert.equal(a.sgp30Read(0),-1);state.bufReads=[[3,32,0,0,12,0]];a.sgp30Measure();assert.equal(a.sgp30Read(1),-1);a.sgp30Init();assert.equal(a.sgp30Read(0),-1)});
test('WebSocket: invalid token, close payload and nonminimal length rejected',()=>{for(const raw of[masked('x',8),'\x81\xfe\x00\x01\x01\x02\x03\x04y']){const {w,sent}=wsEnv();w.feed(0,handshake);w.feed(0,raw);assert.equal(sent.at(-1)[1][0],0x88);assert.equal(w.sendText(0,'x'),false)}const {w,sent}=wsEnv();w.feed(0,handshake.replace('Connection: Upgrade','Connection: notupgrade'));assert(sent[0][1].toString().startsWith('HTTP/1.1 400'))});
function transport(){const e=env();e.state.onString=s=>e.state.rx.push(Buffer.from(s.startsWith('AT+CIPSEND=')?'\r\n> ':'\r\nOK\r\n'));e.state.onWrite=()=>e.state.rx.push(Buffer.from('\r\nSEND OK\r\n'));e.c.WiFi08.wsServerStart(8080);return e}
function ipd(data){return Buffer.from('+IPD,0,'+Buffer.byteLength(data,'latin1')+':'+data,'latin1')}
test('ESP-AT transport: split IPD, UTF8 byte length, prompt and SEND OK',()=>{const e=transport(),w=e.c.WiFi08;e.state.rx.push(ipd(handshake.slice(0,50)));e.tick();e.state.rx.push(ipd(handshake.slice(50)));e.tick();assert(e.state.writes.some(x=>x[0]==='serialB'&&Buffer.from(x[1]).toString().startsWith('HTTP/1.1 101')));e.state.rx.push(ipd(masked('온도,25')));e.tick();assert.equal(w.wsGetReceived(),'온도,25');w.wsSend('한글');assert.equal(w.wsSendSucceeded(),true);assert(e.state.writes.some(x=>x[0]==='serialS'&&x[1]==='AT+CIPSEND=0,9\r\n'));const last=e.state.writes.filter(x=>x[0]==='serialB').at(-1);assert.equal(Buffer.from(last[1]).subarray(2).toString(),'한글\n')});
test('ESP-AT transport: IPD payload cannot fake prompt or SEND OK',()=>{for(const fakePrompt of[true,false]){const e=transport(),w=e.c.WiFi08;e.state.rx.push(ipd(handshake));e.tick();const before=e.state.writes.filter(x=>x[0]==='serialB').length;if(fakePrompt)e.state.onString=s=>{if(s.startsWith('AT+CIPSEND='))e.state.rx.push(ipd('> SEND OK'))};else e.state.onWrite=()=>e.state.rx.push(ipd('SEND OK'));w.wsSend('x');assert.equal(w.wsSendSucceeded(),false);assert.equal(e.state.writes.filter(x=>x[0]==='serialB').length,before+(fakePrompt?0:1))}});
const results=[];for(const [name,fn]of cases){try{fn();results.push({name,passed:true})}catch(e){results.push({name,passed:false,error:String(e.stack||e)})}}
const report={checkedAt:new Date().toISOString(),passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length,hardwareTested:false,results};
fs.mkdirSync(path.join(root,'_research/stability-20261008'),{recursive:true});fs.writeFileSync(path.join(root,'_research/stability-20261008/runtime-results.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify({...report,results:results.filter(r=>!r.passed)},null,2));if(report.failed)process.exitCode=1;
